// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {filemanager} from '../models';

export function CargarConfiguracion():Promise<config.Settings>;

export function CheckLicense():Promise<boolean>;

export function DeleteFile(arg1:string):Promise<void>;

export function EnviarEscaneos(arg1:string,arg2:Array<string>):Promise<filemanager.SendReport>;

export function GetSettings():Promise<config.Settings>;

export function GuardarConfiguracion(arg1:config.Settings):Promise<void>;

export function ListPDFs(arg1:string):Promise<Array<filemanager.FileInfo>>;

export function ListarArchivosPDF(arg1:string):Promise<Array<filemanager.FileInfo>>;

export function ObtenerContenidoPDF(arg1:string):Promise<string>;

export function ReadPDFBase64(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SeleccionarCarpeta(arg1:string):Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SendFiles(arg1:string,arg2:Array<string>):Promise<filemanager.SendReport>;

export function VerificarLicencia():Promise<boolean>;
