// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CargarConfiguracion() {
  return window['go']['main']['App']['CargarConfiguracion']();
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function EnviarEscaneos(arg1, arg2) {
  return window['go']['main']['App']['EnviarEscaneos'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GuardarConfiguracion(arg1) {
  return window['go']['main']['App']['GuardarConfiguracion'](arg1);
}

export function ListPDFs(arg1) {
  return window['go']['main']['App']['ListPDFs'](arg1);
}

export function ListarArchivosPDF(arg1) {
  return window['go']['main']['App']['ListarArchivosPDF'](arg1);
}

export function ObtenerContenidoPDF(arg1) {
  return window['go']['main']['App']['ObtenerContenidoPDF'](arg1);
}

export function ReadPDFBase64(arg1) {
  return window['go']['main']['App']['ReadPDFBase64'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SeleccionarCarpeta(arg1) {
  return window['go']['main']['App']['SeleccionarCarpeta'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SendFiles(arg1, arg2) {
  return window['go']['main']['App']['SendFiles'](arg1, arg2);
}

export function VerificarLicencia() {
  return window['go']['main']['App']['VerificarLicencia']();
}
